const GET_LIST_LINK = 'GET_LIST_LINK'
const ADD_LINK = 'ADD_LINK'
const REMOVE_LINK = 'REMOVE_LINK'
const REMOVE_LINK_ALL = 'REMOVE_LINK_ALL'

export {
  GET_LIST_LINK, ADD_LINK, REMOVE_LINK, REMOVE_LINK_ALL
}